//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Armor_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Armor_info()
        {
            this.Classes_build = new HashSet<Classes_build>();
            this.Classes_build1 = new HashSet<Classes_build>();
            this.Classes_build2 = new HashSet<Classes_build>();
            this.Classes_build3 = new HashSet<Classes_build>();
        }
    
        public string A_ID { get; set; }
        public string A_Name { get; set; }
        public Nullable<short> Inmunity { get; set; }
        public Nullable<short> Robustness { get; set; }
        public Nullable<short> Focus { get; set; }
        public Nullable<short> Vitality { get; set; }
        public Nullable<short> Poise { get; set; }
        public Nullable<short> Phy_guard { get; set; }
        public Nullable<short> Phy_slash { get; set; }
        public Nullable<short> Phy_strike { get; set; }
        public Nullable<short> Phy_thurst { get; set; }
        public Nullable<short> Mag_guard { get; set; }
        public Nullable<short> Fie_guard { get; set; }
        public Nullable<short> Holy_guard { get; set; }
        public double Weigth { get; set; }
        public string ET_ID { get; set; }
    
        public virtual Equipment_Type Equipment_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classes_build> Classes_build { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classes_build> Classes_build1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classes_build> Classes_build2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classes_build> Classes_build3 { get; set; }
    }
}
