//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.Classes_build = new HashSet<Classes_build>();
        }
    
        public string Class_ID { get; set; }
        public string Class_Name { get; set; }
        public short Vigor { get; set; }
        public short Mind { get; set; }
        public short Endurance { get; set; }
        public short Strength { get; set; }
        public short Dex { get; set; }
        public short Intell { get; set; }
        public short Fai { get; set; }
        public short Levels { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classes_build> Classes_build { get; set; }
    }
}
