//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment_info()
        {
            this.Classes_build = new HashSet<Classes_build>();
            this.Classes_build1 = new HashSet<Classes_build>();
            this.Classes_build2 = new HashSet<Classes_build>();
            this.Classes_build3 = new HashSet<Classes_build>();
            this.Classes_build4 = new HashSet<Classes_build>();
            this.Classes_build5 = new HashSet<Classes_build>();
        }
    
        public string E_ID { get; set; }
        public string E_Name { get; set; }
        public short Phy_dame { get; set; }
        public Nullable<short> Phy_guard { get; set; }
        public Nullable<short> Mag_dame { get; set; }
        public Nullable<short> Mag_guard { get; set; }
        public Nullable<short> Fire_dame { get; set; }
        public Nullable<short> Fire_guard { get; set; }
        public Nullable<short> Ligh_dame { get; set; }
        public Nullable<short> Ligh_guard { get; set; }
        public Nullable<short> Holy_dame { get; set; }
        public Nullable<short> Holy_guard { get; set; }
        public Nullable<short> Critboot { get; set; }
        public Nullable<short> Guardboot { get; set; }
        public Nullable<double> Weigth { get; set; }
        public string Scl_Str { get; set; }
        public string Scl_Dex { get; set; }
        public string Scl_Int { get; set; }
        public string Scl_Fai { get; set; }
        public Nullable<short> R_Scl_Str { get; set; }
        public Nullable<short> R_Scl_Dex { get; set; }
        public Nullable<short> R_Scl_Int { get; set; }
        public Nullable<short> R_Scl_Fai { get; set; }
        public string ET_ID { get; set; }
        public string Scl_Arc { get; set; }
        public Nullable<short> R_Scl_Arc { get; set; }
        public string Skill_name { get; set; }
        public string SCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classes_build> Classes_build { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classes_build> Classes_build1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classes_build> Classes_build2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classes_build> Classes_build3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classes_build> Classes_build4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classes_build> Classes_build5 { get; set; }
        public virtual Equipment_Type Equipment_Type { get; set; }
    }
}
