//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stat
    {
        public int Stat_ID { get; set; }
        public Nullable<int> HP { get; set; }
        public Nullable<int> FP { get; set; }
        public Nullable<int> Stamina { get; set; }
        public Nullable<double> Eload { get; set; }
        public Nullable<double> Phy_def { get; set; }
        public Nullable<double> Mag_def { get; set; }
        public Nullable<double> Holy_def { get; set; }
        public Nullable<double> Arc_vita { get; set; }
    }
}
